FROM python:3.14-slim

EXPOSE 8001

WORKDIR /workspace/backend/python

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY ./backend/python/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt\
    && rm -rf /tmp/pip-tmp
